spring.application.name=marketplace

spring.datasource.url=jdbc:mysql://localhost:3306/marketplace_db
spring.datasource.username=root
spring.datasource.password=Arjun@2004

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arjunabhishek.r@gmail.com
spring.mail.password=zeak lfnk kzak nmno
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=dsk35uzxc
cloudinary.api-key=448128425441698
cloudinary.api-secret=9EgGZpw8hEeTwNkF5h0fLOxZWb4

cashfree.app-id=TEST11078909cc70c9b4553223f6b38c90987011
cashfree.secret-key=cfsk_ma_test_3b50858c3e605602ceb6b901c967b702_285d6417
cashfree.env=TEST

cashfree.appId=TEST11078909cc70c9b4553223f6b38c90987011
cashfree.secretKey=cfsk_ma_test_3b50858c3e605602ceb6b901c967b702_285d6417
cashfree.baseUrl=https://sandbox.cashfree.com/pg